service-rating-app:
  container_name: rating-app
  build: .
  ports:
   - "10020:80"
  environment:
   - DEBUG=1
   - REDIS_HOST=redis
  volumes:
   - .:/opt/rating_service/repository
  links:
   - service-rating-redis:redis
  command: "--reload --access-logfile '-' --error-logfile '-'"
service-rating-redis:
  container_name: rating-redis
  image: redis